### ISSUE TITLE
Consider Removing numpy Dep

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#3]
Numpy is really huge. Installation would be much faster if you dropped the numpy dep and did the audio chunking in pure stdlib Python.

**Comment by strob** [comment]
As far as I'm concerned, having access to Numpy (and the surrounding tools) is just about the whole reason for wrapping Kaldi's IO in python!

**Comment by maxhawkins** [comment]
Agreed, numpy is great for prototyping. However, it's a pretty heavy dep if it's just going to be used to split a byte buffer. Are you planning to do more sophisticated stuff with it in the future?

Losing the dependency doesn't stop you from using numpy in code that calls the library. I think it would make people much more likely to use the library if they don't have to install as many things.

**Comment by strob** [comment]
I’d be open to a patch that softened the Numpy dependency in standard_kaldi.py.
The main difference would be that “push_chunk” would take a string instead of a numpy array.

The `transcribe` function is a messy piece of work, which depends on `numm3.py` which in turn depends on Numpy. I’m less enthusiastic about refactoring that one… Every little thing (like adding a cross fade to avoid clipping in an output remix) is easier when you’re working with Numpy arrays. 

Is it really so huge? Looking at it now, I am seeing an installed size of the Ubuntu package <http://packages.ubuntu.com/trusty/python-numpy> is 8.5mb, plus maybe another 6 or 7mb of dependencies. Plus the package is pre-compiled, so it only adds a few seconds.

On OS X, I `dependencies_osx.sh` pulls Numpy from PIP, which is admittedly slow. We could also get it from homebrew, though that might lead to some OS X python conflicts.

**Comment by maxhawkins** [comment]
Here's a change that makes standard_kaldi use wav support from the standard library. This removes the numpy dep and makes the FFMPEG one optional:
https://github.com/maxhawkins/gentle/compare/master...maxhawkins:stdlib_wav

File size isn't really what I'm worried about with depending on numpy. It's more about the complexity of the library. With a library so monolithic there are bound to be complications. Just look at the [number of stackoverflow issues](http://stackoverflow.com/search?q=numpy+install) with people installing numpy. I think it's better to keep things simple.
